addons:
  apt:
    packages:
    - libgmp-dev

language: generic

cache:
  directories:
  - $HOME/.local/bin
  - $HOME/.stack

sudo: required

os:
- linux
- osx

before_install:
- bash tools/install-stack.sh

script:
- stack setup
- stack build --ghc-options -O2 --pedantic
- stack test --ghc-options -O2 --pedantic